// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8rrdyt2a_Mc_GTsag9GYskvEK_rM6DU',
    appId: '1:446971617055:web:2e26dde5647137f2dc5a2a',
    messagingSenderId: '446971617055',
    projectId: 'school-fees-ease-6d0ea',
    authDomain: 'school-fees-ease-6d0ea.firebaseapp.com',
    storageBucket: 'school-fees-ease-6d0ea.appspot.com',
    measurementId: 'G-QJXERY5ZZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_DzVrwIXZZgWkfcZm-F34lW5j3N8REs',
    appId: '1:446971617055:android:fff737f5212a7005dc5a2a',
    messagingSenderId: '446971617055',
    projectId: 'school-fees-ease-6d0ea',
    storageBucket: 'school-fees-ease-6d0ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWBAfL9sBWAJYPKE37Jf5WgsWOkgc7vQ',
    appId: '1:446971617055:ios:277f524924483ee9dc5a2a',
    messagingSenderId: '446971617055',
    projectId: 'school-fees-ease-6d0ea',
    storageBucket: 'school-fees-ease-6d0ea.appspot.com',
    iosBundleId: 'com.example.schoolFeesEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWBAfL9sBWAJYPKE37Jf5WgsWOkgc7vQ',
    appId: '1:446971617055:ios:69b17cec7e23f9f4dc5a2a',
    messagingSenderId: '446971617055',
    projectId: 'school-fees-ease-6d0ea',
    storageBucket: 'school-fees-ease-6d0ea.appspot.com',
    iosBundleId: 'com.example.schoolFeesEase.RunnerTests',
  );
}
